### ISSUE TITLE
Example page broken because of old jQuery version

### ISSUE THREAD

**Issue by devsnd** [bramp/js-sequence-diagrams#68] opened 2014-05-27 22:30 UTC
The example page at https://bramp.github.io/js-sequence-diagrams/ does not work. My browser (firefox 28) complains:

    Error: https://bramp.github.io/js-sequence-diagrams/sequence-diagram-min.js is being assigned a //# sourceMappingURL, but already has one
    ReferenceError: $ is not defined

This can probably be [resolved by using a newer jQuery version](https://stackoverflow.com/questions/21759662/file-is-being-assigned-a-sourcemappingurl-but-already-has-one)

Changing the line 191 in the index.html from

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>

to 

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

should do the job.

---------------------
Edit: I just downloaded the page and applied the fix and it does indeed work then.

**Comment by bramp** [comment] 2015-05-19 04:38
Sorry for not investigating this earlier. I seem unable to reproduce this issue myself, and I have since updated to the latest version of jquery.

I'm going to close this bug, but feel free to reopen if the issue is persisting.

**Closed by bramp** 2015-05-19 04:38 UTC

**Comment by devsnd** [comment] 2015-05-20 09:07
No biggie. Better Nate than Lever. :+1:
