### ISSUE TITLE
space before actor names are trimmed but spaces after are significant, leading to duplicates if not careful

### ISSUE THREAD

**Issue by eviltester** [bramp/js-sequence-diagrams#121] opened 2015-07-14 12:26 UTC
```
Title: Issue: space before actor names are trimmed\nbut spaces after are significant\nleading to duplicates if not careful
A->B : here
B ->A : back atcha
# duplicate A
```

**Comment by bramp** [comment] 2015-07-26 19:12
I can't reproduce this on Chrome or Firefox. It might have been fixed in 16f8ec957e0de19eb1a15432 Could you confirm it still occurs using the latest checked in code?

**Comment by ronkphillips** [comment] 2015-09-20 23:14
Hi, still seems to be an issue with latest (d5caf2). Here's a sample that should repro:
>Title: Here is a title
>Apple->Banana: yo
>Banana-->Cherry : apple says yo
>Note left of Cherry: hey!
>Cherry-->Apple: hey, what's up?
>Cherry->Egg: apple just said yo
>Egg->Apple: Hey apple
>Cherry->>Date: Did you hear that apple said yo?
>Date-->>Apple: Back atcha

**Comment by ashsearle** [comment] 2016-02-29 18:09
Hi Andrew,

It certainly looks like you fixed this in the master, but [your demo site](https://bramp.github.io/js-sequence-diagrams/) still shows the bug because it's running from the `gh-pages` branch.

**Comment by bramp** [comment] 2016-12-28 01:10
This has long since been fixed in code, and on the demo site.

**Closed by bramp** 2016-12-28 01:10 UTC
Labels: bug
